import * as Speech from "expo-speech";
import { AudioContext } from "react-native-audio-api";
import type { AudioBuffer, AudioBufferSourceNode } from "react-native-audio-api";

import { rateForSpeechRate } from "./rate";
import { DEFAULT_VOICE, type SpeechEngine, type TtsVoice } from "./types";

/**
 * Normalized lookup key -> bundled asset, one full set per offered voice.
 * Generated by scripts/generate_voice_bank.py into
 * assets/audio/voice/<voice>/ -- see docs/PRD.md's addendum and
 * PROJECT_FACTS.md for the vocabulary this covers (numbers, punches incl.
 * lead/rear + body variants, kicks, defense/movement words, and Phase
 * 12c's six colour names for the Color Call drill) and why.
 * Adding a voice here means adding it to `TtsVoice`/`VOICE_OPTIONS` in
 * ./types.ts and to generate_voice_bank.py's VOICES list too -- all three
 * have to agree.
 */
const BUNDLED_CLIPS: Record<TtsVoice, Record<string, number>> = {
  am_michael: {
    one: require("../../../assets/audio/voice/am_michael/one.wav"),
    two: require("../../../assets/audio/voice/am_michael/two.wav"),
    three: require("../../../assets/audio/voice/am_michael/three.wav"),
    four: require("../../../assets/audio/voice/am_michael/four.wav"),
    five: require("../../../assets/audio/voice/am_michael/five.wav"),
    six: require("../../../assets/audio/voice/am_michael/six.wav"),

    jab: require("../../../assets/audio/voice/am_michael/jab.wav"),
    cross: require("../../../assets/audio/voice/am_michael/cross.wav"),
    lead_hook: require("../../../assets/audio/voice/am_michael/lead_hook.wav"),
    rear_hook: require("../../../assets/audio/voice/am_michael/rear_hook.wav"),
    body_hook: require("../../../assets/audio/voice/am_michael/body_hook.wav"),
    body_jab: require("../../../assets/audio/voice/am_michael/body_jab.wav"),
    body_cross: require("../../../assets/audio/voice/am_michael/body_cross.wav"),
    lead_uppercut: require("../../../assets/audio/voice/am_michael/lead_uppercut.wav"),
    rear_uppercut: require("../../../assets/audio/voice/am_michael/rear_uppercut.wav"),

    lead_high_kick: require("../../../assets/audio/voice/am_michael/lead_high_kick.wav"),
    rear_high_kick: require("../../../assets/audio/voice/am_michael/rear_high_kick.wav"),
    lead_body_kick: require("../../../assets/audio/voice/am_michael/lead_body_kick.wav"),
    rear_body_kick: require("../../../assets/audio/voice/am_michael/rear_body_kick.wav"),
    lead_low_kick: require("../../../assets/audio/voice/am_michael/lead_low_kick.wav"),
    rear_low_kick: require("../../../assets/audio/voice/am_michael/rear_low_kick.wav"),
    lead_calf_kick: require("../../../assets/audio/voice/am_michael/lead_calf_kick.wav"),
    rear_calf_kick: require("../../../assets/audio/voice/am_michael/rear_calf_kick.wav"),
    lead_inside_kick: require("../../../assets/audio/voice/am_michael/lead_inside_kick.wav"),
    rear_inside_kick: require("../../../assets/audio/voice/am_michael/rear_inside_kick.wav"),
    lead_push_kick: require("../../../assets/audio/voice/am_michael/lead_push_kick.wav"),
    rear_push_kick: require("../../../assets/audio/voice/am_michael/rear_push_kick.wav"),

    roll: require("../../../assets/audio/voice/am_michael/roll.wav"),
    slip: require("../../../assets/audio/voice/am_michael/slip.wav"),
    duck: require("../../../assets/audio/voice/am_michael/duck.wav"),
    pivot: require("../../../assets/audio/voice/am_michael/pivot.wav"),
    check: require("../../../assets/audio/voice/am_michael/check.wav"),
    clinch: require("../../../assets/audio/voice/am_michael/clinch.wav"),

    red: require("../../../assets/audio/voice/am_michael/red.wav"),
    blue: require("../../../assets/audio/voice/am_michael/blue.wav"),
    green: require("../../../assets/audio/voice/am_michael/green.wav"),
    yellow: require("../../../assets/audio/voice/am_michael/yellow.wav"),
    orange: require("../../../assets/audio/voice/am_michael/orange.wav"),
    purple: require("../../../assets/audio/voice/am_michael/purple.wav"),
  },
  am_eric: {
    one: require("../../../assets/audio/voice/am_eric/one.wav"),
    two: require("../../../assets/audio/voice/am_eric/two.wav"),
    three: require("../../../assets/audio/voice/am_eric/three.wav"),
    four: require("../../../assets/audio/voice/am_eric/four.wav"),
    five: require("../../../assets/audio/voice/am_eric/five.wav"),
    six: require("../../../assets/audio/voice/am_eric/six.wav"),

    jab: require("../../../assets/audio/voice/am_eric/jab.wav"),
    cross: require("../../../assets/audio/voice/am_eric/cross.wav"),
    lead_hook: require("../../../assets/audio/voice/am_eric/lead_hook.wav"),
    rear_hook: require("../../../assets/audio/voice/am_eric/rear_hook.wav"),
    body_hook: require("../../../assets/audio/voice/am_eric/body_hook.wav"),
    body_jab: require("../../../assets/audio/voice/am_eric/body_jab.wav"),
    body_cross: require("../../../assets/audio/voice/am_eric/body_cross.wav"),
    lead_uppercut: require("../../../assets/audio/voice/am_eric/lead_uppercut.wav"),
    rear_uppercut: require("../../../assets/audio/voice/am_eric/rear_uppercut.wav"),

    lead_high_kick: require("../../../assets/audio/voice/am_eric/lead_high_kick.wav"),
    rear_high_kick: require("../../../assets/audio/voice/am_eric/rear_high_kick.wav"),
    lead_body_kick: require("../../../assets/audio/voice/am_eric/lead_body_kick.wav"),
    rear_body_kick: require("../../../assets/audio/voice/am_eric/rear_body_kick.wav"),
    lead_low_kick: require("../../../assets/audio/voice/am_eric/lead_low_kick.wav"),
    rear_low_kick: require("../../../assets/audio/voice/am_eric/rear_low_kick.wav"),
    lead_calf_kick: require("../../../assets/audio/voice/am_eric/lead_calf_kick.wav"),
    rear_calf_kick: require("../../../assets/audio/voice/am_eric/rear_calf_kick.wav"),
    lead_inside_kick: require("../../../assets/audio/voice/am_eric/lead_inside_kick.wav"),
    rear_inside_kick: require("../../../assets/audio/voice/am_eric/rear_inside_kick.wav"),
    lead_push_kick: require("../../../assets/audio/voice/am_eric/lead_push_kick.wav"),
    rear_push_kick: require("../../../assets/audio/voice/am_eric/rear_push_kick.wav"),

    roll: require("../../../assets/audio/voice/am_eric/roll.wav"),
    slip: require("../../../assets/audio/voice/am_eric/slip.wav"),
    duck: require("../../../assets/audio/voice/am_eric/duck.wav"),
    pivot: require("../../../assets/audio/voice/am_eric/pivot.wav"),
    check: require("../../../assets/audio/voice/am_eric/check.wav"),
    clinch: require("../../../assets/audio/voice/am_eric/clinch.wav"),

    red: require("../../../assets/audio/voice/am_eric/red.wav"),
    blue: require("../../../assets/audio/voice/am_eric/blue.wav"),
    green: require("../../../assets/audio/voice/am_eric/green.wav"),
    yellow: require("../../../assets/audio/voice/am_eric/yellow.wav"),
    orange: require("../../../assets/audio/voice/am_eric/orange.wav"),
    purple: require("../../../assets/audio/voice/am_eric/purple.wav"),
  },
};

export function normalizeToKey(text: string): string {
  return text
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

export function resolveBundledClip(text: string, voice: TtsVoice = DEFAULT_VOICE): number | null {
  const key = normalizeToKey(text);
  const clips = BUNDLED_CLIPS[voice];
  return key in clips ? clips[key] : null;
}

function gainForVolume(appVolume: number): number {
  return Math.min(1, Math.max(0, appVolume));
}

/**
 * Gap between consecutive words in a spoken combo -- without this, "Jab,
 * Cross, Lead Hook" schedules all three clips at the same instant (they
 * were previously fired via a synchronous forEach with no offset, see
 * useSession.ts), so they play stacked on top of each other: unintelligible
 * and, since summed waveforms can exceed full scale, audibly distorted.
 * 0.12s mirrors the clapper's own inter-repeat gap (audio/service.ts's
 * CLAPPER_GAP_SEC) -- short enough to still read as one fluid combo.
 */
const WORD_GAP_SEC = 0.12;

export { rateForSpeechRate } from "./rate";

/**
 * `voice` is fixed for this engine's lifetime -- it selects which of
 * BUNDLED_CLIPS' voice-keyed buffer sets gets decoded at construction,
 * unlike setRate/setVolume which stay live-adjustable after the fact.
 * Switching voices means creating a new engine (next session/screen
 * mount), not hot-swapping mid-utterance -- the underlying audio data is
 * genuinely different per voice, there's nothing to "adjust" in place.
 */
export function createSpeechEngine(voice: TtsVoice = DEFAULT_VOICE): SpeechEngine {
  const context = new AudioContext();
  const volumeGain = context.createGain();
  volumeGain.connect(context.destination);

  const clips = BUNDLED_CLIPS[voice];
  const buffers = (Object.keys(clips) as string[]).reduce(
    (acc, key) => {
      acc[key] = context.decodeAudioData(clips[key]);
      return acc;
    },
    {} as Record<string, Promise<AudioBuffer>>,
  );

  let currentRate = 1.0;

  /**
   * Every source still connected to the output bus. Tracked for two
   * reasons, both real bugs found on a device (2026-08-26):
   *
   * 1. A source used to be created, connected and started, then never
   *    disconnected. Finished nodes stayed wired into `volumeGain`
   *    forever, so the graph grew with every word spoken -- roughly 110
   *    of them over a 12-round Color Call session -- and audio latency
   *    climbed with it. That was the "the bell gets delayed on later
   *    rounds" report.
   * 2. Nothing could silence playback already in flight, so overlapping
   *    utterances stacked instead of replacing each other -- the "echo".
   */
  const activeSources = new Set<AudioBufferSourceNode>();

  /**
   * Bumped by every stop()/playWord/playCombo. `playSequence` decodes
   * asynchronously between words, so without this a superseded combo
   * would keep scheduling its remaining words onto the clock after a
   * newer one had already started -- stopping the *current* sources
   * alone wouldn't catch them.
   */
  let playGeneration = 0;

  function releaseSource(source: AudioBufferSourceNode): void {
    activeSources.delete(source);
    try {
      source.disconnect();
    } catch {
      // Already torn down (e.g. the context closed under it) -- the only
      // goal here is that it stops referencing the bus.
    }
  }

  function stop(): void {
    playGeneration += 1;
    for (const source of [...activeSources]) {
      try {
        source.stop();
      } catch {
        // Already ended; releasing it below is all that's left to do.
      }
      releaseSource(source);
    }
    // The TTS fallback plays through the OS, not this bus, so it needs
    // its own stop -- otherwise an unrecognized word keeps talking over
    // whatever replaced it.
    Speech.stop();
  }

  function setVolume(appVolume: number): void {
    volumeGain.gain.value = gainForVolume(appVolume);
  }
  setVolume(1.0);

  function setRate(rate: number): void {
    currentRate = rateForSpeechRate(rate);
  }

  // Schedules a bundled clip to start at AudioContext time `when` (rather
  // than "now") so a caller can line up several clips back-to-back on the
  // context's own clock -- see playSequence. Returns the clip's real
  // playback duration (buffer.duration adjusted for the active rate) so
  // the caller can compute the next clip's start time.
  async function scheduleBuffer(key: string, when: number, generation: number): Promise<number> {
    const buffer = await buffers[key];
    // Superseded while this clip was decoding -- scheduling it now would
    // play a word from an utterance the caller has already replaced.
    if (generation !== playGeneration) {
      return 0;
    }
    // pitchCorrection: true -- react-native-audio-api's native WSOLA
    // time-stretch, the whole point of this sub-phase (docs/PRD.md's
    // "real unsolved technical requirement").
    const source = context.createBufferSource({ pitchCorrection: true });
    source.buffer = buffer;
    source.playbackRate.value = currentRate;
    source.connect(volumeGain);
    // Self-releasing, so a finished word stops weighing on the graph.
    source.onEnded = () => releaseSource(source);
    activeSources.add(source);
    source.start(when);
    return buffer.duration / currentRate;
  }

  async function play(key: string, generation: number): Promise<void> {
    await scheduleBuffer(key, context.currentTime, generation);
  }

  /**
   * Speaks each word in sequence rather than all at once -- the bug this
   * fixes: useSession.ts used to call playWord once per punch in a combo
   * with no delay between calls, so every word in a combo started at the
   * same instant. Bundled clips are scheduled on the AudioContext's own
   * clock (precise, no JS-timer drift, same pattern as the clapper's
   * repeat scheduling); a word with no bundled clip falls through to
   * on-device TTS, which has no such clock to schedule against, so that
   * step genuinely awaits its onDone callback before continuing.
   */
  async function playSequence(texts: string[], generation: number): Promise<void> {
    let when = context.currentTime;
    for (const text of texts) {
      // A newer playWord/playCombo/stop has taken over -- abandon the rest
      // of this combo rather than scheduling it behind the new one.
      if (generation !== playGeneration) {
        return;
      }
      const trimmed = text.trim();
      if (trimmed === "") {
        continue;
      }
      const key = normalizeToKey(trimmed);
      if (key in clips) {
        const durationSec = await scheduleBuffer(key, when, generation);
        when += durationSec + WORD_GAP_SEC;
      } else {
        await new Promise<void>((resolve) => {
          Speech.speak(trimmed, {
            rate: currentRate,
            volume: volumeGain.gain.value,
            onDone: () => resolve(),
            onStopped: () => resolve(),
            onError: () => resolve(),
          });
        });
        when = context.currentTime + WORD_GAP_SEC;
      }
    }
  }

  function playWord(text: string): boolean {
    if (text.trim() === "") {
      return false;
    }
    // Replace, don't layer -- see SpeechEngine.stop's note on the echo
    // this fixes. Done after the blank-text guard so a no-op call can't
    // cut off speech that is legitimately still playing.
    stop();
    const generation = playGeneration;
    const key = normalizeToKey(text);
    if (key in clips) {
      // Fire-and-forget: playWord's own contract is synchronous (existing
      // callers, and this engine's test suite, rely on an immediate
      // boolean return -- see service.test.ts), so a decode/playback
      // failure here can't be reported back through this call's return
      // value. Still must not become an unhandled promise rejection.
      play(key, generation).catch(() => {});
      return true;
    }
    // No library can synthesize TTS to a cacheable file (PROJECT_FACTS.md
    // -- neither expo-speech nor react-native-tts support it, only a
    // custom native module would), so an unrecognized word falls through
    // to live on-device synthesis every time it's spoken, through the
    // OS's own audio output rather than this engine's AudioContext bus.
    // Speaks the original text, not the normalized key.
    Speech.speak(text, { rate: currentRate, volume: volumeGain.gain.value });
    return true;
  }

  function playCombo(texts: string[]): void {
    // Replace, don't layer -- the "Intense" built-in's 1s combo gap is
    // shorter than a 3-4 punch combo takes to speak, so without this the
    // next combo started underneath the previous one.
    stop();
    // Same fire-and-forget contract as playWord -- see its comment above.
    playSequence(texts, playGeneration).catch(() => {});
  }

  function close(): Promise<void> {
    stop();
    return context.close();
  }

  return { setVolume, setRate, playWord, playCombo, stop, close };
}
