import * as Speech from "expo-speech";
import { AudioContext } from "react-native-audio-api";
import type { AudioBuffer } from "react-native-audio-api";

import type { SpeechEngine } from "./types";

/**
 * Normalized lookup key -> bundled asset. Generated by
 * scripts/generate_voice_bank.py into assets/audio/voice/ -- see
 * docs/PRD.md's addendum and PROJECT_FACTS.md for the vocabulary this
 * covers (numbers, punches incl. lead/rear + body variants, kicks,
 * defense/movement words) and why. Committed WAVs are silent placeholders
 * until that script is actually run (no Python in this environment).
 */
const BUNDLED_CLIPS: Record<string, number> = {
  one: require("../../../assets/audio/voice/one.wav"),
  two: require("../../../assets/audio/voice/two.wav"),
  three: require("../../../assets/audio/voice/three.wav"),
  four: require("../../../assets/audio/voice/four.wav"),
  five: require("../../../assets/audio/voice/five.wav"),
  six: require("../../../assets/audio/voice/six.wav"),

  jab: require("../../../assets/audio/voice/jab.wav"),
  cross: require("../../../assets/audio/voice/cross.wav"),
  lead_hook: require("../../../assets/audio/voice/lead_hook.wav"),
  rear_hook: require("../../../assets/audio/voice/rear_hook.wav"),
  body_hook: require("../../../assets/audio/voice/body_hook.wav"),
  body_jab: require("../../../assets/audio/voice/body_jab.wav"),
  body_cross: require("../../../assets/audio/voice/body_cross.wav"),
  lead_uppercut: require("../../../assets/audio/voice/lead_uppercut.wav"),
  rear_uppercut: require("../../../assets/audio/voice/rear_uppercut.wav"),

  lead_high_kick: require("../../../assets/audio/voice/lead_high_kick.wav"),
  rear_high_kick: require("../../../assets/audio/voice/rear_high_kick.wav"),
  lead_body_kick: require("../../../assets/audio/voice/lead_body_kick.wav"),
  rear_body_kick: require("../../../assets/audio/voice/rear_body_kick.wav"),
  lead_low_kick: require("../../../assets/audio/voice/lead_low_kick.wav"),
  rear_low_kick: require("../../../assets/audio/voice/rear_low_kick.wav"),
  lead_calf_kick: require("../../../assets/audio/voice/lead_calf_kick.wav"),
  rear_calf_kick: require("../../../assets/audio/voice/rear_calf_kick.wav"),
  lead_inside_kick: require("../../../assets/audio/voice/lead_inside_kick.wav"),
  rear_inside_kick: require("../../../assets/audio/voice/rear_inside_kick.wav"),
  lead_push_kick: require("../../../assets/audio/voice/lead_push_kick.wav"),
  rear_push_kick: require("../../../assets/audio/voice/rear_push_kick.wav"),

  roll: require("../../../assets/audio/voice/roll.wav"),
  slip: require("../../../assets/audio/voice/slip.wav"),
  duck: require("../../../assets/audio/voice/duck.wav"),
  pivot: require("../../../assets/audio/voice/pivot.wav"),
  check: require("../../../assets/audio/voice/check.wav"),
  clinch: require("../../../assets/audio/voice/clinch.wav"),
};

export function normalizeToKey(text: string): string {
  return text
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

export function resolveBundledClip(text: string): number | null {
  const key = normalizeToKey(text);
  return key in BUNDLED_CLIPS ? BUNDLED_CLIPS[key] : null;
}

function gainForVolume(appVolume: number): number {
  return Math.min(1, Math.max(0, appVolume));
}

/**
 * Clamped to [0.25, 4.0] -- react-native-audio-api's native WSOLA
 * time-stretch hard-caps playbackRate at a fixed C++ constant
 * (WsolaTimeStretcher::MAX_PLAYBACK_RATE = 4), confirmed 2026-08-24
 * reading its source. Revised down from an originally-discussed 5x
 * rather than building extra complexity (e.g. a second pre-compressed
 * buffer per clip) to work around a fixed native ceiling -- see
 * PROJECT_FACTS.md.
 */
export function rateForSpeechRate(speechRate: number): number {
  return Math.min(4.0, Math.max(0.25, speechRate));
}

export function createSpeechEngine(): SpeechEngine {
  const context = new AudioContext();
  const volumeGain = context.createGain();
  volumeGain.connect(context.destination);

  const buffers = (Object.keys(BUNDLED_CLIPS) as string[]).reduce(
    (acc, key) => {
      acc[key] = context.decodeAudioData(BUNDLED_CLIPS[key]);
      return acc;
    },
    {} as Record<string, Promise<AudioBuffer>>,
  );

  let currentRate = 1.0;

  function setVolume(appVolume: number): void {
    volumeGain.gain.value = gainForVolume(appVolume);
  }
  setVolume(1.0);

  function setRate(rate: number): void {
    currentRate = rateForSpeechRate(rate);
  }

  async function play(key: string): Promise<void> {
    const buffer = await buffers[key];
    // pitchCorrection: true -- react-native-audio-api's native WSOLA
    // time-stretch, the whole point of this sub-phase (docs/PRD.md's
    // "real unsolved technical requirement").
    const source = context.createBufferSource({ pitchCorrection: true });
    source.buffer = buffer;
    source.playbackRate.value = currentRate;
    source.connect(volumeGain);
    source.start();
  }

  function playWord(text: string): boolean {
    if (text.trim() === "") {
      return false;
    }
    const key = normalizeToKey(text);
    if (key in BUNDLED_CLIPS) {
      void play(key);
      return true;
    }
    // No library can synthesize TTS to a cacheable file (PROJECT_FACTS.md
    // -- neither expo-speech nor react-native-tts support it, only a
    // custom native module would), so an unrecognized word falls through
    // to live on-device synthesis every time it's spoken, through the
    // OS's own audio output rather than this engine's AudioContext bus.
    // Speaks the original text, not the normalized key.
    Speech.speak(text, { rate: currentRate, volume: volumeGain.gain.value });
    return true;
  }

  return { setVolume, setRate, playWord };
}
