import { AudioContext } from "react-native-audio-api";
import type { AudioBuffer } from "react-native-audio-api";

import type { SpeechEngine } from "./types";

/**
 * Normalized lookup key -> bundled asset. Generated by
 * scripts/generate_voice_bank.py into assets/audio/voice/ -- see
 * docs/PRD.md's addendum and PROJECT_FACTS.md for the vocabulary this
 * covers (numbers, punches incl. lead/rear + body variants, kicks,
 * defense/movement words) and why. Committed WAVs are silent placeholders
 * until that script is actually run (no Python in this environment).
 */
const BUNDLED_CLIPS: Record<string, number> = {
  one: require("../../../assets/audio/voice/one.wav"),
  two: require("../../../assets/audio/voice/two.wav"),
  three: require("../../../assets/audio/voice/three.wav"),
  four: require("../../../assets/audio/voice/four.wav"),
  five: require("../../../assets/audio/voice/five.wav"),
  six: require("../../../assets/audio/voice/six.wav"),

  jab: require("../../../assets/audio/voice/jab.wav"),
  cross: require("../../../assets/audio/voice/cross.wav"),
  lead_hook: require("../../../assets/audio/voice/lead_hook.wav"),
  rear_hook: require("../../../assets/audio/voice/rear_hook.wav"),
  body_hook: require("../../../assets/audio/voice/body_hook.wav"),
  body_jab: require("../../../assets/audio/voice/body_jab.wav"),
  body_cross: require("../../../assets/audio/voice/body_cross.wav"),
  lead_uppercut: require("../../../assets/audio/voice/lead_uppercut.wav"),
  rear_uppercut: require("../../../assets/audio/voice/rear_uppercut.wav"),

  lead_high_kick: require("../../../assets/audio/voice/lead_high_kick.wav"),
  rear_high_kick: require("../../../assets/audio/voice/rear_high_kick.wav"),
  lead_body_kick: require("../../../assets/audio/voice/lead_body_kick.wav"),
  rear_body_kick: require("../../../assets/audio/voice/rear_body_kick.wav"),
  lead_low_kick: require("../../../assets/audio/voice/lead_low_kick.wav"),
  rear_low_kick: require("../../../assets/audio/voice/rear_low_kick.wav"),
  lead_calf_kick: require("../../../assets/audio/voice/lead_calf_kick.wav"),
  rear_calf_kick: require("../../../assets/audio/voice/rear_calf_kick.wav"),
  lead_inside_kick: require("../../../assets/audio/voice/lead_inside_kick.wav"),
  rear_inside_kick: require("../../../assets/audio/voice/rear_inside_kick.wav"),
  lead_push_kick: require("../../../assets/audio/voice/lead_push_kick.wav"),
  rear_push_kick: require("../../../assets/audio/voice/rear_push_kick.wav"),

  roll: require("../../../assets/audio/voice/roll.wav"),
  slip: require("../../../assets/audio/voice/slip.wav"),
  duck: require("../../../assets/audio/voice/duck.wav"),
  pivot: require("../../../assets/audio/voice/pivot.wav"),
  check: require("../../../assets/audio/voice/check.wav"),
  clinch: require("../../../assets/audio/voice/clinch.wav"),
};

export function normalizeToKey(text: string): string {
  return text
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

export function resolveBundledClip(text: string): number | null {
  const key = normalizeToKey(text);
  return key in BUNDLED_CLIPS ? BUNDLED_CLIPS[key] : null;
}

function gainForVolume(appVolume: number): number {
  return Math.min(1, Math.max(0, appVolume));
}

export function createSpeechEngine(): SpeechEngine {
  const context = new AudioContext();
  const volumeGain = context.createGain();
  volumeGain.connect(context.destination);

  const buffers = (Object.keys(BUNDLED_CLIPS) as string[]).reduce(
    (acc, key) => {
      acc[key] = context.decodeAudioData(BUNDLED_CLIPS[key]);
      return acc;
    },
    {} as Record<string, Promise<AudioBuffer>>,
  );

  function setVolume(appVolume: number): void {
    volumeGain.gain.value = gainForVolume(appVolume);
  }
  setVolume(1.0);

  async function play(key: string): Promise<void> {
    const buffer = await buffers[key];
    const source = context.createBufferSource();
    source.buffer = buffer;
    source.connect(volumeGain);
    source.start();
  }

  function playWord(text: string): boolean {
    const key = normalizeToKey(text);
    if (!(key in BUNDLED_CLIPS)) {
      return false;
    }
    void play(key);
    return true;
  }

  return { setVolume, playWord };
}
